# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: bio-signalp 0.3.1 ruby lib

Gem::Specification.new do |s|
  s.name = "bio-signalp"
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Ben J Woodcroft"]
  s.date = "2014-08-04"
  s.description = "A wrapper for the signal peptide prediction algorith SignalP. Not very well supported, but seems to work for the author, at least."
  s.email = "donttrustben near gmail.com"
  s.executables = ["signalp.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/signalp.rb",
    "bio-signalp.gemspec",
    "lib/bio-signalp.rb",
    "lib/bio/appl/common.rb",
    "lib/bio/appl/signalp3.rb",
    "lib/bio/appl/signalp4.rb",
    "spec/bio-signalp_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/wwood/bioruby-signalp"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "A wrapper for the signal peptide prediction algorith SignalP"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bio>, [">= 1.4.1", "~> 1.4"])
      s.add_runtime_dependency(%q<bio-logger>, ["~> 1.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.21", "~> 1.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
    else
      s.add_dependency(%q<bio>, [">= 1.4.1", "~> 1.4"])
      s.add_dependency(%q<bio-logger>, ["~> 1.0"])
      s.add_dependency(%q<rspec>, ["~> 2.8"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<bundler>, [">= 1.0.21", "~> 1.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
    end
  else
    s.add_dependency(%q<bio>, [">= 1.4.1", "~> 1.4"])
    s.add_dependency(%q<bio-logger>, ["~> 1.0"])
    s.add_dependency(%q<rspec>, ["~> 2.8"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<bundler>, [">= 1.0.21", "~> 1.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
  end
end

